name: Playwright API Tests CI

# Triggers: on push or pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies
      - run: npm ci

      # Step 4: Lint and auto-fix code with ESLint
      - run: npx eslint . --fix

      # Step 5: Check code formatting with Prettier
      - run: npx prettier --check .

      # Step 6: Run Playwright tests
      - run: npx playwright test